# Generated by Django 2.2.1 on 2019-08-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('words', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('date_added', models.DateField(auto_now=True)),
                ('ISBN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.Book')),
            ],
        ),
    ]
