# Generated by Django 2.2.1 on 2019-08-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together={('ISBN', 'words')},
        ),
    ]
