# Generated by Django 2.2.1 on 2019-08-07 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_auto_20190807_1705'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vocabulary',
            unique_together=set(),
        ),
    ]
